stages:
  - lint
  - test
  - release
  - build
  - deploy

variables:
  DOCKER_IMAGE: alpine:latest
  UV_LINK_MODE: copy

.default-tags:
  tags:
    - docker-runner

pre-commit:
  stage: lint
  extends: .default-tags
  image: python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${ADEF_INTG_TOKEN}@git.icf.gob.hn/alopez/adef-integ-tools.git"
  script:
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install pre-commit
    - pre-commit install
    - pre-commit run -a || true
    - |
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
        git diff --quiet || (git add -u && git commit -m "Auto-format with pre-commit")
        git pull --rebase origin $CI_COMMIT_REF_NAME || true
        git push origin HEAD:$CI_COMMIT_REF_NAME
      fi
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ".venv/"
      - ${PRE_COMMIT_HOME}
    policy: pull-push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: false

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  tags: [docker-runner]

container_scanning:
  tags: [docker-runner]
  variables:
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE/$CI_DEFAULT_BRANCH:$CI_COMMIT_SHA

secret_detection:
  tags: [docker-runner]

build-linux:
  stage: release
  extends: .default-tags
  image: python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${ADEF_INTG_TOKEN}@git.icf.gob.hn/alopez/adef-integ-tools.git"
  script:
    - uv venv .venv
    - source .venv/bin/activate
    - uv pip install pyinstaller
    - pyinstaller adef-intg.spec
    - if [ ! -f dist/adef-intg/adef-intg ]; then echo "Binario no encontrado"; exit 1; fi
    - echo "🚀 Subiendo binario como asset al release de GitLab..."
    - |
      curl --silent --fail --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links" \
        --header "PRIVATE-TOKEN: ${ADEF_INTG_TOKEN}" \
        --form "name=adef-intg Linux Binary" \
        --form "url=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/dist/adef-intg/adef-intg"
  artifacts:
    paths:
      - dist/adef-intg/adef-intg
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "web"'

build-windows:
  stage: release
  extends: .default-tags
  image: cibuilds/wine:latest
  script:
    - apt-get update && apt-get install -y python3 python3-pip
    - python3 -m pip install --upgrade pip
    - python3 -m pip install uv
    - uv pip install -r requirements.txt
    - uv pip install pyinstaller
    - pyinstaller adef-intg.spec --onefile --distpath dist/windows
    - echo "📁 Validando binario generado..."
    - test -f dist/windows/adef-intg.exe || (echo "❌ Binario no encontrado"; exit 1)

    - echo "🚀 Subiendo como asset a la Release..."
    - |
      curl --silent --fail --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links" \
        --header "PRIVATE-TOKEN: ${ADEF_INTG_TOKEN}" \
        --form "name=adef-intg Windows Binary" \
        --form "url=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/dist/windows/adef-intg.exe"
  artifacts:
    paths:
      - dist/windows/adef-intg.exe
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "web"'

.test-template: &test-template
  stage: test
  extends: .default-tags
  image: docker.io/python:${PYTHON_VERSION}
  before_script:
    - pip install uv
  script:
    - uv venv
    - uv pip install .
    - uv run python -c "import adef_intg; print('adef_intg import successful')"

test:matrix:
  parallel:
    matrix:
      - PYTHON_VERSION: "3.10"
      - PYTHON_VERSION: "3.11"
      - PYTHON_VERSION: "3.12"
  <<: *test-template

build_and_release:
  stage: deploy
  extends: .default-tags
  image: python:3.12
  variables:
    PACKAGE_NAME: "adef-intg"
    DIST_DIR: "dist"
    GITLAB_API: "https://git.icf.gob.hn/api/v4"
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot1:${TAG_CI_TOKE}@git.icf.gob.hn/alopez/adef-integ-tools.git"
    - uv venv .venv
    - source .venv/bin/activate
  script:
    - uv pip install -e .[build]
    - uv build

    - |
      TAG="${CI_COMMIT_TAG}"
      RELEASE_NAME="Release ${TAG}"
      echo "Creating or updating release ${TAG}"
      create_response=$(curl --silent --header "PRIVATE-TOKEN: ${TAG_CI_TOKE}" \
        --request POST \
        --data "name=${RELEASE_NAME}&tag_name=${TAG}&description=Automated release for ${PACKAGE_NAME} ${TAG}" \
        "${GITLAB_API}/projects/${CI_PROJECT_ID}/releases")

      echo "Release creation response:"
      echo "$create_response"

    - |
      for file in ${DIST_DIR}/*; do
        echo "Uploading ${file} to project uploads..."
        upload_response=$(curl --silent --header "PRIVATE-TOKEN: ${TAG_CI_TOKE}" \
          --form "file=@${file}" \
          "${GITLAB_API}/projects/${CI_PROJECT_ID}/uploads")

        url=$(echo "$upload_response" | python -c "import sys, json; print(json.load(sys.stdin).get('url', ''))")
        name=$(basename "${file}")

        if [ -z "$url" ]; then
          echo "Upload failed or 'url' not found. Response:"
          echo "$upload_response"
          exit 1
        fi

        echo "Linking ${name} to release ${TAG}"
        curl --header "PRIVATE-TOKEN: ${TAG_CI_TOKE}" \
          --request POST \
          --data "name=${name}&url=${CI_PROJECT_URL}${url}" \
          "${GITLAB_API}/projects/${CI_PROJECT_ID}/releases/${TAG}/assets/links"
      done
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always