stages:
  - lint
  - test
  - release
  - build
  - deploy
  - auto-bump

variables:
  DOCKER_IMAGE: alpine:latest
  UV_LINK_MODE: copy
  GIT_DEPTH: 0

.default-tags:
  tags:
    - docker-runner

pre-commit:
  stage: lint
  extends: .default-tags
  image: docker.io/python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${ADEF_INTG_TOKEN}@git.icf.gob.hn/alopez/adef-tools.git"
  script:
    - uv venv
    - source .venv/bin/activate
    - uv pip install pre-commit
    - pre-commit install
    - pre-commit run -a || true
    - |
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
        git diff --quiet || (git add -u && git commit -m "Auto-format with pre-commit")
        # git pull --rebase origin $CI_COMMIT_REF_NAME || true
        git push origin HEAD:$CI_COMMIT_REF_NAME
      fi
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ".venv/"
      - ${PRE_COMMIT_HOME}
    policy: pull-push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: false

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

sast:
  tags: [docker-runner]

container_scanning:
  tags: [docker-runner]
  variables:
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE/$CI_DEFAULT_BRANCH:$CI_COMMIT_SHA

secret_detection:
  tags: [docker-runner]

build-linux:
  stage: build
  extends: .default-tags
  image: docker.io/python:3.12
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${CI_TAG_REL_TOKEN}@git.icf.gob.hn/alopez/adef-tools.git"
  script:
    - uv venv
    - source .venv/bin/activate
    - uv pip install pyinstaller
    - pyinstaller adef-tools.spec
    - if [ ! -f dist/adef-tools/adef-tools ]; then echo "Binario no encontrado"; exit 1; fi
    - echo "🚀 Subiendo binario como asset al release de GitLab..."
    - |
      curl --silent --fail --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links" \
        --header "PRIVATE-TOKEN: ${CI_TAG_REL_TOKEN}" \
        --form "name=adef-intg Linux Binary" \
        --form "url=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/dist/adef-tools/adef-tools"
  artifacts:
    paths:
      - dist/adef-tools/adef-tools
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG'

# build-windows:
#   stage: build
#   extends: .default-tags
#   image: cibuilds/wine:latest
#   script:
#     - apt-get update && apt-get install -y python3 python3-pip
#     - python3 -m pip install --upgrade pip
#     - python3 -m pip install uv
#     - uv pip install -r requirements.txt
#     - uv pip install pyinstaller
#     - pyinstaller adef-tools.spec --onefile --distpath dist/windows
#     - echo "📁 Validando binario generado..."
#     - test -f dist/windows/adef-intg.exe || (echo "❌ Binario no encontrado"; exit 1)

#     - echo "🚀 Subiendo como asset a la Release..."
#     - |
#       curl --silent --fail --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links" \
#         --header "PRIVATE-TOKEN: ${CI_TAG_REL_TOKEN}" \
#         --form "name=adef-intg Windows Binary" \
#         --form "url=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/dist/windows/adef-tools.exe"
#   artifacts:
#     paths:
#       - dist/windows/adef-tools.exe
#     expire_in: 1 week
#   rules:
#     - if: '$CI_COMMIT_TAG'

.test-template: &test-template
  stage: test
  extends: .default-tags
  image: docker.io/python:${PYTHON_VERSION}
  before_script:
    - pip install uv
    - uv venv
    # - uv pip install .
  script:
    - uv run python -c "import adef_tools; print('adef-tools import successful')"

test:matrix:
  parallel:
    matrix:
      - PYTHON_VERSION: "3.10"
      - PYTHON_VERSION: "3.11"
      - PYTHON_VERSION: "3.12"
      - PYTHON_VERSION: "3.13"
  <<: *test-template

build_and_release:
  stage: deploy
  extends: .default-tags
  image: python:3.12
  variables:
    PACKAGE_NAME: "adef-tools"
    DIST_DIR: "dist"
    GITLAB_API: "https://git.icf.gob.hn/api/v4"
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${CI_TAG_REL_TOKEN}@git.icf.gob.hn/alopez/adef-tools.git"
    - uv venv
    - source .venv/bin/activate
  dependencies:
    - test:matrix
  script:
    - uv pip install twine
    - uv build

    - |
      TAG="${CI_COMMIT_TAG}"
      RELEASE_NAME="Release ${TAG}"
      echo "Creating or updating release ${TAG}"
      create_response=$(curl --silent --header "PRIVATE-TOKEN: ${CI_TAG_REL_TOKEN}" \
        --request POST \
        --data "name=${RELEASE_NAME}&tag_name=${TAG}&description=Automated release for ${PACKAGE_NAME} ${TAG}" \
        "${GITLAB_API}/projects/${CI_PROJECT_ID}/releases")

      echo "Release creation response:"
      echo "$create_response"

    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

    - TWINE_USERNAME=${PYPI_USERNAME} TWINE_PASSWORD=${PYPI_PASSWORD} twine upload dist/*
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always

auto-bump:
  stage: auto-bump
  extends: .default-tags
  image: python:3.9
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - git config --global user.email "ci-runner@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "http://project_9_bot:${CI_TAG_REL_TOKEN}@git.icf.gob.hn/alopez/adef-tools.git"
    - uv venv
    - source .venv/bin/activate
    - uv pip install -U commitizen
    - uv pip install -U cz-changeup
  dependencies:
    - test:matrix
  script:
    - |
      set -e
      NEXT_TAG=$(cz bump --get-next 2>&1) || true
      if echo "$NEXT_TAG" | grep -q '\[NO_COMMITS_TO_BUMP\]'; then
        echo "No commits elegibles para bump. Saliendo exitosamente."
        exit 0
      fi
      NEXT_TAG="v$NEXT_TAG"
      git tag -d "$NEXT_TAG" || true
      if git show-ref --verify --quiet refs/heads/main; then git branch -D main; fi
      git checkout main
      cz bump --yes
      git push origin main:$CI_COMMIT_REF_NAME
      TAG=v$(cz version -p)
      echo "#!/bin/sh" > variables
      echo "export TAG='$TAG'" >> variables
      git push origin --tags
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE !~ /bump:/'

  artifacts:
    paths:
      - variables
