name: adef-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - mamba
  - gdal
  - libgdal
  - libgdal-arrow-parquet
  - pip
  - pip:
    - .
    - affine==2.4.0
    - attrs==25.3.0
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.2.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - dask==2025.4.1
    - distributed==2025.4.1
    - fonttools==4.58.0
    - fsspec==2025.3.2
    - geopandas==1.0.1
    - idna==3.10
    - importlib-metadata==8.7.0
    - jinja2==3.1.6
    - kiwisolver==1.4.8
    - locket==1.0.0
    - lxml==5.4.0
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - msgpack==1.1.0
    - numpy==2.2.5
    - owslib==0.33.0
    - packaging==25.0
    - pandas==2.2.3
    - partd==1.4.2
    - pillow==11.2.1
    - psutil==7.0.0
    - pyogrio==0.11.0
    - pyparsing==3.2.3
    - pyproj==3.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - rasterio==1.4.3
    - requests==2.32.3
    - rioxarray==0.19.0
    - shapely==2.1.0
    - six==1.17.0
    - sortedcontainers==2.4.0
    - tblib==3.1.0
    - toolz==1.0.0
    - tornado==6.4.2
    - tzdata==2025.2
    - urllib3==2.4.0
    - xarray==2025.4.0
    - zict==3.0.0
    - zipp==3.21.0
