name: adef-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - mamba
  - gdal
  - libgdal
  - libgdal-arrow-parquet
  - pip
  - pip:
    - .
    - affine==2.4.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - argcomplete==3.6.2
    - attrs==25.3.0
    - bracex==2.5.post1
    - bump-my-version==1.1.2
    - certifi==2025.4.26
    - cfgv==3.4.0
    - charset-normalizer==3.4.2
    - click==8.2.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - commitizen==4.7.0
    - contourpy==1.3.2
    - cycler==0.12.1
    - dask==2025.4.1
    - decli==0.6.2
    - distlib==0.3.9
    - distributed==2025.4.1
    - exceptiongroup==1.3.0
    - filelock==3.18.0
    - fonttools==4.58.0
    - fsspec==2025.3.2
    - geopandas==1.0.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - identify==2.6.10
    - idna==3.10
    - importlib-metadata==8.7.0
    - jinja2==3.1.6
    - kiwisolver==1.4.8
    - locket==1.0.0
    - lxml==5.4.0
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - msgpack==1.1.0
    - nodeenv==1.9.1
    - numpy==2.2.5
    - owslib==0.33.0
    - packaging==25.0
    - pandas==2.2.3
    - partd==1.4.2
    - pillow==11.2.1
    - pip==25.1.1
    - platformdirs==4.3.8
    - pre-commit==4.2.0
    - prompt-toolkit==3.0.51
    - psutil==7.0.0
    - pyarrow==20.0.0
    - pydantic==2.11.4
    - pydantic-core==2.33.2
    - pydantic-settings==2.9.1
    - pygments==2.19.1
    - pyogrio==0.11.0
    - pyparsing==3.2.3
    - pyproj==3.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytz==2025.2
    - pyyaml==6.0.2
    - questionary==2.1.0
    - rasterio==1.4.3
    - requests==2.32.3
    - rich==14.0.0
    - rich-click==1.8.8
    - rioxarray==0.19.0
    - shapely==2.1.0
    - six==1.17.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - tblib==3.1.0
    - termcolor==2.5.0
    - tomlkit==0.13.2
    - toolz==1.0.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - typing-extensions==4.13.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - virtualenv==20.31.2
    - wcmatch==10.0
    - wcwidth==0.2.13
    - xarray==2025.4.0
    - zict==3.0.0
    - zipp==3.21.0
